package turbine.om;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Sun Apr 14 22:50:47 IST 2019]
 *
 *  You should add additional methods to this class to meet the
 *  application requirements.  This class will only be generated as
 *  long as it does not already exist in the output directory.
 */
public class TurbineRolePermissionPeer
    extends turbine.om.BaseTurbineRolePermissionPeer
{
    /** Serial version */
    private static final long serialVersionUID = 1555262447731L;

}
